version: '3.2'

services:
  geth: 
    image:
      ethereum/client-go:alpine
    ports:
      - "8545"
      - "30303"
    volumes:
      - $HOME/srv/geth:/root/.ethereum
    command: --rpcvhosts geth --rpc --rpcaddr "0.0.0.0" --syncmode "light" --cache 1024 --rpc
    logging:
      options:
        max-size: "50m"
    networks:
      - scrapers-network
    deploy:
      mode: global
      restart_policy:
        delay: 2s
        window: 20s

  erc20:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/diadata/blockchain-scrapers/blockchains/ethereum/node/Dockerfile-erc20
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_erc20
    command: -symbol BNB -address "0xB8c77482e45F1F44dE1745F52C74426C631bDD52"
    networks:
      - scrapers-network
    depends_on:
      - geth
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata

  eth:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/diadata/blockchain-scrapers/blockchains/ethereum/node/Dockerfile-eth
    image: ${DOCKER_HUB_LOGIN}/blockchain-scrapers_eth
    networks:
      - scrapers-network
    depends_on: 
      - geth
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata

secrets:
  api_diadata:
    file: $GOPATH/src/github.com/diadata-org/diadata/blockchain-scrapers/config/secrets/api_diadata.json

volumes: 
  bitcoin:

networks: 
  scrapers-network: