version: '3.2'
services:

  genericassetcollector:
    build:
      context: ../../../..
      dockerfile: github.com/diadata-org/diadata/build/Dockerfile-assetCollectionService
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_genericassetcollector:latest
    restart: "no"
    networks:
      - redis-network
      - postgres-network
    environment:
      - EXEC_MODE=production
    secrets:
      - postgres_credentials
    logging:
      options:
        max-size: "50m"


  uniswapassetcollector:
    depends_on: [genericassetcollector]
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_genericassetcollector:latest
    command: /bin/assetCollectionService -source=Uniswap
    logging:
      options:
        max-size: "50m"
    environment:
      - EXEC_MODE=production
    networks:
      - redis-network
      - postgres-network
    secrets:
      - postgres_credentials

  sushiswapassetcollector:
    depends_on: [genericassetcollector]
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_genericassetcollector:latest
    command: /bin/assetCollectionService -source=SushiSwap
    logging:
      options:
        max-size: "50m"
    environment:
      - EXEC_MODE=production
    networks:
      - redis-network
      - postgres-network
    secrets:
      - postgres_credentials

  pancakeswapassetcollector:
    depends_on: [genericassetcollector]
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_genericassetcollector:latest
    command: /bin/assetCollectionService -source=PanCakeSwap
    logging:
      options:
        max-size: "50m"
    environment:
      - EXEC_MODE=production
    networks:
      - redis-network
      - postgres-network
    secrets:
      - postgres_credentials
    
  nonethassetcollector:
    depends_on: [genericassetcollector]
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_genericassetcollector:latest
    command: /bin/assetCollectionService -source=assetlists -secret=non_eth_assets
    logging:
      options:
        max-size: "50m"
    environment:
      - EXEC_MODE=production
    networks:
      - redis-network
      - postgres-network
    secrets:
      - postgres_credentials

  fiatassetcollector:
    depends_on: [genericassetcollector]
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_genericassetcollector:latest
    command: /bin/assetCollectionService -source=assetlists -secret=fiat_assets
    logging:
      options:
        max-size: "50m"
    environment:
      - EXEC_MODE=production
    networks:
      - redis-network
      - postgres-network
    secrets:
      - postgres_credentials

secrets:
  api_binance:
    file: ../secrets/api_binance.json
  api_bitfinex:
    file: ../secrets/api_bitfinex.json
  api_kraken:
    file: ../secrets/api_kraken.json
  postgres_credentials:
    file: ../secrets/postgres_credentials.txt

networks:
  kafka-network:
    external:
        name: kafka_kafka-network
  redis-network:
    external:
        name: redis_redis-network
  influxdb-network:
    external:
        name: influxdb_influxdb-network
  postgres-network:
    external:
        name: postgres_postgres-network
