version: '3.2'
services:

  tradesblockservice:
    build:
      context: ../../../..
      dockerfile: github.com/diadata-org/diadata/build/Dockerfile-tradesBlockService
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_tradesblockservice:latest
    networks:
      - kafka-network
      - redis-network
      - influxdb-network
    logging:
      options:
        max-size: "50m"
    volumes:
      - /home/srv/config:/config
    environment:
      - EXEC_MODE=production
  
  filtersblockservice:
    build:
      context: ../../../..
      dockerfile: github.com/diadata-org/diadata/build/Dockerfile-filtersBlockService
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_filtersblockservice:latest
    networks:
      - kafka-network
      - redis-network
      - influxdb-network
    environment:
      - EXEC_MODE=production
    logging:
      options:
        max-size: "50m"

  graphservice:
    build:
      context: ../../../..
      dockerfile: github.com/diadata-org/diadata/build/Dockerfile-graphService
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_graphservice:latest
    networks:
      - redis-network
      - influxdb-network
    volumes:
      - /home/srv/restServer/charts:/charts
    environment:
      - EXEC_MODE=production
    logging:
      options:
        max-size: "50m"

  # itinservice:
  #   build:
  #     context: ../../../..
  #     dockerfile: github.com/diadata-org/diadata/build/Dockerfile-itinService
  #   image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_itinservice:latest
  #   networks:
  #     - redis-network
  #     - influxdb-network
  #   environment:
  #     - EXEC_MODE=production
  #   logging:
  #     options:
  #       max-size: "50m"

  indexcalculationservice:
    build:
      context: ../../../..
      dockerfile: github.com/diadata-org/diadata/build/Dockerfile-indexCalculationService
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_indexcalculationservice:latest
    networks:
      - redis-network
      - influxdb-network
    environment:
      - EXEC_MODE=production
    logging:
      options:
        max-size: "50m"

  cviservice:
    build:
      context: ../../../..
      dockerfile: github.com/diadata-org/diadata/build/Dockerfile-cviService
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_cviservice:latest
    networks:
      - redis-network
      - influxdb-network
    environment:
      - EXEC_MODE=production
    logging:
      options:
        max-size: "50m"

  ethcviservice:
    build:
      context: ../../../..
      dockerfile: github.com/diadata-org/diadata/build/Dockerfile-cviServiceEth
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_ethcviservice:latest
    networks:
      - redis-network
      - influxdb-network
    environment:
      - EXEC_MODE=production
    logging:
      options:
        max-size: "50m"

  pairdiscoveryservice:
    build:
      context: ../../../..
      dockerfile: github.com/diadata-org/diadata/build/Dockerfile-pairDiscoveryService
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_pairdiscoveryservice:latest
    networks:
      - redis-network
    environment:
      - EXEC_MODE=production
    logging:
      options:
        max-size: "50m"

  supplyservice:
    build:
      context: ../../../..
      dockerfile: github.com/diadata-org/diadata/build/Dockerfile-supplyService
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_supplyservice:latest
    networks:
      - redis-network
      - influxdb-network
    environment:
      - EXEC_MODE=production
    logging:
      options:
        max-size: "50m"

networks:
  kafka-network:
    external:
        name: kafka_kafka-network
  redis-network:
    external:
        name: redis_redis-network
  influxdb-network:
    external:
        name: influxdb_influxdb-network
