#alias influxcli="docker exec -it `docker ps | grep influx | cut -f1 -d\ ` influx"

version: '3.2'
services:

  influxdb:
#    ports:
#      - "8086:8086"
    environment:
      - EXEC_MODE=production

    image: influxdb
    volumes:
      - /home/srv/influxdb:/var/lib/influxdb
    networks:
      - influxdb-network
    environment:
      INFLUXDB_HTTP_MAX_BODY_SIZE: 0
    logging:
      options:
        max-size: "50m" 

networks:
  influxdb-network:
    driver: overlay
    attachable: true