version: '3.2'

services:
  cardano:
    image:
      diadata/cardano-explorer-docker
    volumes:
      - /home/srv/cardano:/home/cardano/cardano-sl/state-explorer-mainnet
    logging:
      options:
        max-size: "50m"
    networks:
      - scrapers-network
    deploy:
      mode: global
      restart_policy:
        delay: 2s
        window: 20s

  ada:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/diadata/build/Dockerfile-ada
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_ada
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata

secrets:
  api_diadata:
    file: $GOPATH/src/github.com/diadata-org/diadata/secrets/api_diadata.json

volumes: 
  cardano:

networks: 
  scrapers-network: