version: '3.2'

services:
  monero:
    image:
      ${DOCKER_HUB_LOGIN}/blockchain-scrapers_monero
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/diadata/blockchain-scrapers/blockchains/monero/node/Dockerfile-monero
    ports:
      - "18080"
      - "18081"
    volumes:
      - $HOME/srv/monero:/root/.bitmonero
    networks:
      - scrapers-network

  xmr:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/diadata/blockchain-scrapers/blockchains/monero/node/Dockerfile-xmr
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_xmr
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata

secrets:
  api_diadata:
    file: $GOPATH/src/github.com/diadata-org/diadata/blockchain-scrapers/config/secrets/api_diadata.json

volumes: 
  bitcoin:

networks: 
  scrapers-network: