basePath: /
definitions:
  dia.Pair:
    properties:
      exchange:
        type: string
      foreignName:
        type: string
      symbol:
        type: string
    type: object
  dia.Supply:
    properties:
      circulatingSupply:
        type: number
      name:
        type: string
      source:
        type: string
      symbol:
        type: string
      time:
        type: string
    type: object
  dia.Trade:
    properties:
      estimatedUSDPrice:
        type: number
      foreignTradeID:
        type: string
      pair:
        type: string
      price:
        type: number
      source:
        type: string
      symbol:
        type: string
      time:
        type: string
      volume:
        type: number
    type: object
  diaApi.Coin:
    properties:
      circulatingSupply:
        type: number
      name:
        type: string
      price:
        type: number
      priceYesterday:
        type: number
      symbol:
        type: string
      time:
        type: string
      volumeYesterdayUSD:
        type: number
    type: object
  diaApi.CoinSymbolAndName:
    properties:
      name:
        type: string
      symbol:
        type: string
    type: object
  diaApi.Coins:
    properties:
      change:
        $ref: '#/definitions/models.Change'
        type: object
      coins:
        items:
          $ref: '#/definitions/diaApi.Coin'
        type: array
      completeCoinList:
        items:
          $ref: '#/definitions/diaApi.CoinSymbolAndName'
        type: array
    type: object
  diaApi.Pairs:
    properties:
      pairs:
        items:
          $ref: '#/definitions/dia.Pair'
        type: array
    type: object
  diaApi.SymbolDetails:
    properties:
      change:
        $ref: '#/definitions/models.Change'
        type: object
      coin:
        $ref: '#/definitions/diaApi.Coin'
        type: object
      exchanges:
        items:
          $ref: '#/definitions/models.SymbolExchangeDetails'
        type: array
    type: object
  diaApi.points:
    properties:
      dataPoints:
        type: string
    type: object
  models.Change:
    properties:
      usd:
        items:
          $ref: '#/definitions/models.CurrencyChange'
        type: array
    type: object
  models.CurrencyChange:
    properties:
      rate:
        type: number
      rateYesterday:
        type: number
      symbol:
        type: string
    type: object
  models.Quotation:
    properties:
      name:
        type: string
      price:
        type: number
      priceYesterday:
        type: number
      source:
        type: string
      symbol:
        type: string
      time:
        type: string
      volumeYesterdayUSD:
        type: number
    type: object
  models.SymbolExchangeDetails:
    properties:
      lastTrades:
        items:
          $ref: '#/definitions/dia.Trade'
        type: array
      name:
        type: string
      price:
        type: number
      priceYesterday:
        type: number
      time:
        type: string
      volumeYesterdayUSD:
        type: number
    type: object
  restApi.APIError:
    properties:
      errorcode:
        type: integer
      errormessage:
        type: string
    type: object
host: api.diadata.org
info:
  contact: {}
  description: The world's crowd-driven financial data community has a professional
    API made for you.<br><h2>Decentral and transparent by design</h2><br>With our
    decentral approach to data verification, you can gain a deep insight into current
    and past pricing, volume and exchange info so you can make the right decisions
    to stay ahead of the game.<br><br><h3>Find the right data for your needs</h3><br>Show
    your users the most transparent data on the market with our API. Whether you're
    building a financial service, a portfolio management tool, a new media offering,
    or more, we have the most advanced and updated data on the market for your product.<br>For
    Oracle usage see [github](https://github.com/diadata-org/diadata/blob/master/documentation/methodology/Oracles.md).<br><br><h3>Backtest
    your strategies</h3><br>Use the most efficient and transparent crypto data to
    run simulations and backtest your trading or investing strategies. With crowd-aggregated
    hundreds of exchanges you can be sure that you're getting the right picture every
    single time.<br><br><h3>Run Experiments</h3><br>Build your own models with our
    data, to further your interest or just for fun. With our flexible and powerful
    API, we provide you with a set of data that will help you draw insights and make
    conclusions.<br><br><h3>Request your data</h3><br>Set a bounty on gitcoin.io or
    drop us [line](mailto:API@diadata.org).
  license:
    name: GNU GPLv3
  title: diadata.org API
  version: "1.0"
paths:
  /v1/chartPoints/:
    get:
      consumes:
      - application/json
      description: Get Symbol Details
      parameters:
      - description: Some symbol
        in: path
        name: symbol
        required: true
        type: string
      - description: Some exchange
        in: path
        name: exchange
        required: true
        type: string
      - description: Some filter
        in: path
        name: filter
        required: true
        type: string
      - description: scale 5m 30m 1h 4h 1d 1w
        in: query
        name: scale
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/diaApi.points'
            type: object
        "404":
          description: Symbol not found
          schema:
            $ref: '#/definitions/restApi.APIError'
            type: object
        "500":
          description: error
          schema:
            $ref: '#/definitions/restApi.APIError'
            type: object
      summary: Get chart points for
      tags:
      - dia
  /v1/chartPointsAllExchanges/:
    get:
      consumes:
      - application/json
      description: Get Symbol Details
      parameters:
      - description: Some symbol
        in: path
        name: symbol
        required: true
        type: string
      - description: Some filter
        in: path
        name: filter
        required: true
        type: string
      - description: scale 5m 30m 1h 4h 1d 1w
        in: query
        name: scale
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/diaApi.points'
            type: object
        "404":
          description: Symbol not found
          schema:
            $ref: '#/definitions/restApi.APIError'
            type: object
        "500":
          description: error
          schema:
            $ref: '#/definitions/restApi.APIError'
            type: object
      summary: Get Symbol Details
      tags:
      - dia
  /v1/coins:
    get:
      consumes:
      - application/json
      description: GetCoins
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/diaApi.Coins'
            type: object
        "500":
          description: error
          schema:
            $ref: '#/definitions/restApi.APIError'
            type: object
      summary: Get coins
      tags:
      - dia
  /v1/pairs/:
    get:
      consumes:
      - application/json
      description: Get pairs
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/diaApi.Pairs'
            type: object
        "500":
          description: error
          schema:
            $ref: '#/definitions/restApi.APIError'
            type: object
      summary: Get pairs
      tags:
      - dia
  /v1/quotation/:
    get:
      consumes:
      - application/json
      description: GetQuotation
      parameters:
      - description: Some symbol
        in: path
        name: symbol
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/models.Quotation'
            type: object
        "404":
          description: Symbol not found
          schema:
            $ref: '#/definitions/restApi.APIError'
            type: object
        "500":
          description: error
          schema:
            $ref: '#/definitions/restApi.APIError'
            type: object
      summary: Get quotation
      tags:
      - dia
  /v1/supply:
    post:
      consumes:
      - application/json
      description: Post the circulating supply
      parameters:
      - description: Coin symbol
        in: query
        name: Symbol
        required: true
        type: string
      - description: number of coins in circulating supply
        in: query
        name: CirculatingSupply
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/dia.Supply'
            type: object
        "500":
          description: error
          schema:
            $ref: '#/definitions/restApi.APIError'
            type: object
      summary: Post the circulating supply
      tags:
      - dia
  /v1/supply/:
    get:
      consumes:
      - application/json
      description: GetSupply
      parameters:
      - description: Some symbol
        in: path
        name: symbol
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/dia.Supply'
            type: object
        "404":
          description: Symbol not found
          schema:
            $ref: '#/definitions/restApi.APIError'
            type: object
        "500":
          description: error
          schema:
            $ref: '#/definitions/restApi.APIError'
            type: object
      summary: Get supply
      tags:
      - dia
  /v1/symbol/:
    get:
      consumes:
      - application/json
      description: Get Symbol Details
      parameters:
      - description: Some symbol
        in: path
        name: symbol
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/diaApi.SymbolDetails'
            type: object
        "404":
          description: Symbol not found
          schema:
            $ref: '#/definitions/restApi.APIError'
            type: object
        "500":
          description: error
          schema:
            $ref: '#/definitions/restApi.APIError'
            type: object
      summary: Get Symbol Details
      tags:
      - dia
swagger: "2.0"
